### ISSUE TITLE
How to display help screen

### ISSUE THREAD

**Issue by kdelmonte** [fclp/fluent-command-line-parser#31]
Can you please provide an example on how to display a help screen that list all parameters and their purpose?

**Comment by siywilliams** [comment]
You can setup any help arguments, such as ```-?``` or ```--help``` to print all parameters which have been setup, along with their descriptions to the console by using ```SetupHelp(params string[])```.

For example:
```c#
parser.SetupHelp("?", "help")
 .Callback(text => Console.WriteLine(text));
```

Since v1.4 you can also choose to display the formatted help screen text manually, so that you can display it under other circumstances (see https://github.com/fclp/fluent-command-line-parser/issues/29).

For example:

```c#
var parser = new FluentCommandLineParser<Args>();

parser.SetupHelp("?", "help")
 .Callback(text => Console.WriteLine(text));

// triggers the SetupHelp Callback which writes the text to the console
parser.HelpOption.ShowHelp(parser.Options);
```

**Comment by kdelmonte** [comment]
This worked perfectly. I think it is the only thing missing from the docs. 

Anyways, thank you. This project is great!

**Comment by siywilliams** [comment]
Thanks for the feedback. I'll update the docs to include the help setup.
