### ISSUE TITLE
back slash at end of string option doesnt work

### ISSUE THREAD

**Issue by EricZimmerman** [fclp/fluent-command-line-parser#44]
if i have this:

  p.Setup(arg => arg.Directory)
                .As("Dir")
                .WithDescription("\tDirectory to look for hives (recursively). --Hive or --Dir is required.");

and then call the program like this:

foo.exe --dir "C:\temp\bar" --sk [veris

things work, but if i do this

foo.exe --dir "C:\temp\bar\" --sk [veris

i get this error

Option '--dir' parse error: could not parse 'C:\temp\bar" --sk [veris' to 'System.String'.

seems that last back slash is causing issues. any work around?

**Comment by siywilliams** [comment]
The array passed into <code>static void Main(string[] args)</code> by the .Net framework seems to be different depending on whether you have the final <code>'\'</code> character in it.

[This article](http://weblogs.asp.net/jongalloway//_5B002E00_NET-Gotcha_5D00_-Commandline-args-ending-in-_5C002200_-are-subject-to-CommandLineToArgvW-whackiness) also explains the problem.

Fclp is expecting the .Net framework to have already parsed <code>--dir "C:\temp\bar\" --sk [veris</code> into an array with 4 strings. This doesn't happen as the backslash seems to have escaped some parsing condition which has resulted in 2 strings. As a result it thinks the string <code>"C:\temp\bar\" --sk [veris</code> is the value for the <code>--dir</code> option, which fails to parse because of the whitespace (it thinks the whitespace is seperating another value which is only valid if you're parsing into a <code>List</code>)

<code>--dir "C:\temp\bar" --sk [veris</code>

![2015-07-17 18_30_14-fluentcommandlineparser debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/3663513/8753231/e6b4ab80-2cb1-11e5-9fe3-780eccfa6326.png)

<code>--dir "C:\temp\bar\" --sk [veris</code>

![2015-07-17 18_29_19-fluentcommandlineparser debugging - microsoft visual studio](https://cloud.githubusercontent.com/assets/3663513/8753230/e6b2d4ae-2cb1-11e5-9f18-fed81bb18b7d.png)

**Comment by nelyom** [comment]
I've ended up resolving this via my own parser pulling from Environment.CommandLine, rather than rely on the incoming string[] args.

The funny rules on the .NET (and underneath that CommandLineToArgvW) are easily worked around if a little bit of logic is applied.

I've submitted my little project here.  https://github.com/nelyom/cmdLineTokenizer

**Comment by NTTAKR** [comment]
See also Issue #63
